(* Cross-validation harness for [Cairos_engine.Backtest.run].

   Loads the Pandas-emitted price/signal fixtures, runs the OCaml engine with
   the same conventions encoded in [validation/reference.py:backtest_reference],
   and diffs [equity_curve], [returns], and the trade log against the Pandas
   reference fixtures element-wise.

   Pattern mirrors [test/unit/cairos/cross_validate_frame.ml] and
   [test/unit/cairos_finance/cross_validate.ml]: this is an [executable], not a
   [test]. Fixtures are generated by Python via [just validate-generate], so
   [dune runtest] must not invoke it. The binary runs via [just validate-check].

   Tolerance is absolute [1e-10] on floats;
   exact equality on integers, timestamps, and instrument strings. The
   NaN-aware tolerance comparator handles the leading
   row of [backtest_returns.csv], which is NaN by [Cairos.Series.pct_change]
   semantics, and both operands are [is_nan]-checked before subtraction so a
   regression that emits NaN on one side does not slip through.

   The rebalance bar indices [[2; 7; 12; 17; 22; 27; 32; 37; 42; 47]] are
   hard-coded and must match
   [validation/reference.py:BACKTEST_REBALANCE_BAR_INDICES =
    list(range(2, 50, 5))]. There is no separate rebalance fixture; the
   schedule is encoded as bar indices on both sides. *)

let fixture_dir = "validation/fixtures"
let tolerance = 1e-10
let commission = 0.001
let slippage = 0.0005
let rebalance_bar_indices = [| 2; 7; 12; 17; 22; 27; 32; 37; 42; 47 |]

let die_tooling fmt =
  Printf.ksprintf
    (fun s ->
      prerr_endline ("cross_validate engine (tooling): " ^ s);
      exit 2)
    fmt

let die_mismatch fmt =
  Printf.ksprintf
    (fun s ->
      prerr_endline ("cross_validate engine: " ^ s);
      exit 1)
    fmt

let read_frame_fixture path =
  match Cairos_io.frame_of_csv ~freq:Cairos.Freq.Day path with
  | Ok f -> f
  | Error msg -> die_tooling "%s: %s" path msg

let read_lines path =
  match In_channel.with_open_text path In_channel.input_all with
  | exception Sys_error msg -> die_tooling "%s: %s" path msg
  | content ->
      String.split_on_char '\n' content
      |> List.filter (fun s -> String.length s > 0)

let parse_float ~path ~line s =
  let trimmed = String.trim s in
  if trimmed = "" then Float.nan
  else
    match Float.of_string_opt trimmed with
    | Some v -> v
    | None ->
        die_tooling "%s line %d: cannot parse %S as float" path line trimmed

let parse_int ~path ~line s =
  let trimmed = String.trim s in
  match int_of_string_opt trimmed with
  | Some v -> v
  | None -> die_tooling "%s line %d: cannot parse %S as int" path line trimmed

let parse_ptime ~path ~line s =
  let trimmed = String.trim s in
  match Ptime.of_rfc3339 trimmed with
  | Ok (t, _, _) -> t
  | Error _ ->
      die_tooling "%s line %d: cannot parse %S as RFC 3339" path line trimmed

(* Reads a (timestamp,value) CSV with header. Empty value cells produce
   [Float.nan] (the leading row of [backtest_returns.csv] is one such cell —
   it encodes [Series.pct_change]'s leading-NaN sentinel). The timestamp
   column is informational: the engine's output index is physically shared
   with the price frame's index, so row-order alignment is
   guaranteed by construction. We only validate that each row has two
   columns; timestamps emitted by Pandas as date-only [YYYY-MM-DD] are not
   RFC-3339-parseable without a time-of-day suffix. *)
let read_series_fixture path =
  let lines = read_lines path in
  match lines with
  | [] -> die_tooling "%s: empty file" path
  | header :: rest ->
      if String.trim header <> "timestamp,value" then
        die_tooling "%s: expected header 'timestamp,value', got %S" path
          (String.trim header);
      List.mapi
        (fun i line ->
          let line_num = i + 2 in
          match String.split_on_char ',' line with
          | [ _ts; v ] -> parse_float ~path ~line:line_num v
          | _ ->
              die_tooling "%s line %d: expected 2 columns, got %S" path line_num
                line)
        rest
      |> Array.of_list

type expected_trade = {
  entry_timestamp : Ptime.t;
  exit_timestamp : Ptime.t;
  instrument : string;
  entry_price : float;
  exit_price : float;
  pnl : float;
  holding_period_bars : int;
}

let read_trades_fixture path =
  let lines = read_lines path in
  match lines with
  | [] -> die_tooling "%s: empty file" path
  | header :: rest ->
      let expected_header =
        "entry_timestamp,exit_timestamp,instrument,entry_price,exit_price,pnl,holding_period_bars"
      in
      if String.trim header <> expected_header then
        die_tooling "%s: unexpected header %S" path (String.trim header);
      List.mapi
        (fun i line ->
          let line_num = i + 2 in
          match String.split_on_char ',' line with
          | [ ets; xts; inst; ep; xp; pnl; hpb ] ->
              {
                entry_timestamp = parse_ptime ~path ~line:line_num ets;
                exit_timestamp = parse_ptime ~path ~line:line_num xts;
                instrument = String.trim inst;
                entry_price = parse_float ~path ~line:line_num ep;
                exit_price = parse_float ~path ~line:line_num xp;
                pnl = parse_float ~path ~line:line_num pnl;
                holding_period_bars = parse_int ~path ~line:line_num hpb;
              }
          | _ -> die_tooling "%s line %d: expected 7 columns" path line_num)
        rest
      |> Array.of_list

let float_close ~tol a b =
  let an = Float.is_nan a and bn = Float.is_nan b in
  if an && bn then true
  else if an || bn then false
  else Float.abs (a -. b) <= tol

let compare_float_series ~name ~expected ~actual =
  let elen = Array.length expected in
  let alen = Array.length actual in
  if elen <> alen then
    die_mismatch "%s: length mismatch — expected %d, got %d" name elen alen;
  for i = 0 to elen - 1 do
    let e = expected.(i) and a = actual.(i) in
    if not (float_close ~tol:tolerance e a) then
      die_mismatch "%s: row %d expected %.17g, got %.17g (diff %.17g, tol %g)"
        name i e a
        (Float.abs (e -. a))
        tolerance
  done

let frame_index frame =
  let name = Cairos.Nonempty.hd (Cairos.Frame.columns frame) in
  match Cairos.Frame.get name frame with
  | Some s -> Cairos.Series.index s
  | None -> die_tooling "frame missing column %S" name

let build_rebalance_index price_idx =
  let price_ts = Cairos.Index.timestamps price_idx in
  let n = Array.length price_ts in
  let floats =
    Array.map
      (fun bar ->
        if bar < 0 || bar >= n then
          die_tooling "rebalance bar %d out of price-frame range [0, %d)" bar n;
        Ptime.to_float_s price_ts.(bar))
      rebalance_bar_indices
  in
  match Cairos.Index.of_unix_floats Cairos.Freq.Day floats with
  | Ok idx -> idx
  | Error e -> die_tooling "rebalance index: %s" (Cairos.Index.err_to_string e)

let compare_trades ~expected ~actual =
  let elen = Array.length expected in
  let alen = Array.length actual in
  if elen <> alen then
    die_mismatch "trades: length mismatch — expected %d, got %d" elen alen;
  Array.iteri
    (fun i e ->
      let a : Cairos_engine.Trade.t = actual.(i) in
      if not (Ptime.equal e.entry_timestamp a.entry_timestamp) then
        die_mismatch "trades row %d entry_timestamp: expected %s, got %s" i
          (Ptime.to_rfc3339 e.entry_timestamp)
          (Ptime.to_rfc3339 a.entry_timestamp);
      if not (Ptime.equal e.exit_timestamp a.exit_timestamp) then
        die_mismatch "trades row %d exit_timestamp: expected %s, got %s" i
          (Ptime.to_rfc3339 e.exit_timestamp)
          (Ptime.to_rfc3339 a.exit_timestamp);
      if e.instrument <> a.instrument then
        die_mismatch "trades row %d instrument: expected %S, got %S" i
          e.instrument a.instrument;
      if e.holding_period_bars <> a.holding_period_bars then
        die_mismatch "trades row %d holding_period_bars: expected %d, got %d" i
          e.holding_period_bars a.holding_period_bars;
      if not (float_close ~tol:tolerance e.entry_price a.entry_price) then
        die_mismatch
          "trades row %d entry_price: expected %.17g, got %.17g (diff %.17g)" i
          e.entry_price a.entry_price
          (Float.abs (e.entry_price -. a.entry_price));
      if not (float_close ~tol:tolerance e.exit_price a.exit_price) then
        die_mismatch
          "trades row %d exit_price: expected %.17g, got %.17g (diff %.17g)" i
          e.exit_price a.exit_price
          (Float.abs (e.exit_price -. a.exit_price));
      if not (float_close ~tol:tolerance e.pnl a.pnl) then
        die_mismatch "trades row %d pnl: expected %.17g, got %.17g (diff %.17g)"
          i e.pnl a.pnl
          (Float.abs (e.pnl -. a.pnl)))
    expected

let () =
  let prices_path = Filename.concat fixture_dir "backtest_prices.csv" in
  let signals_path = Filename.concat fixture_dir "backtest_signals.csv" in
  let equity_path = Filename.concat fixture_dir "backtest_equity_curve.csv" in
  let returns_path = Filename.concat fixture_dir "backtest_returns.csv" in
  let trades_path = Filename.concat fixture_dir "backtest_trades.csv" in

  let price_frame = read_frame_fixture prices_path in
  let signal_frame = read_frame_fixture signals_path in
  let price_idx = frame_index price_frame in
  let rebalance_index = build_rebalance_index price_idx in

  let r =
    match
      Cairos_engine.Backtest.run ~price_frame ~signal_frame ~rebalance_index
        ~commission ~slippage
    with
    | Ok r -> r
    | Error e ->
        die_tooling "Backtest.run: %s" (Cairos_engine.Backtest.err_to_string e)
  in

  let expected_equity = read_series_fixture equity_path in
  let expected_returns = read_series_fixture returns_path in
  let expected_trades = read_trades_fixture trades_path in

  let actual_equity = Nx.to_array (Cairos.Series.values r.equity_curve) in
  let actual_returns = Nx.to_array (Cairos.Series.values r.returns) in
  let actual_trades = Array.of_list (Cairos.Nonempty.to_list r.trades) in

  compare_float_series ~name:"equity_curve" ~expected:expected_equity
    ~actual:actual_equity;
  compare_float_series ~name:"returns" ~expected:expected_returns
    ~actual:actual_returns;
  compare_trades ~expected:expected_trades ~actual:actual_trades;

  print_endline "Cross-validate engine: OK";
  exit 0
