(* Cross-validation harness for Cairos.Resample.resample, daily -> monthly.

   Loads the Pandas-emitted dated daily fixture (business days 2024-01-02
   through 2025-03-14, fixed-seed values), resamples it to [Freq.Month] under
   both [`Sum] and [`Last], and diffs the output labels and values against the
   Pandas reference fixtures (validation/reference.py:resample_monthly_reference,
   authored independently from the bucket-start convention, not from
   lib/resample.ml). Exits 0 on full agreement at tolerance 1e-10, 1 on any
   mismatch, 2 on tooling-level failure (missing fixture, malformed CSV).

   Pattern mirrors test/unit/cairos/cross_validate_frame.ml and
   test/unit/cairos_finance/cross_validate.ml: this is an (executable), not a
   (test). Fixtures are generated by Python via `just validate-generate`, so
   `dune runtest` must not invoke it. The binary runs via `just validate-check`
   only. *)

open Cairos

let binary = "cross_validate_resample"
let fixture_dir = Validate_support.generated_fixture_dir
let tolerance = Validate_support.default_tolerance
let die_tooling fmt = Validate_support.die_tooling ~binary fmt
let die_mismatch fmt = Validate_support.die_mismatch ~binary fmt

let read_daily_series ~path :
    ([ `Daily ], (float, Bigarray.float64_elt) Nx.t) Series.t =
  match Cairos_io.of_csv ~freq:Freq.Day path with
  | Ok s -> s
  | Error e -> die_tooling "%s: %s" path (Cairos_io.err_to_string e)

let read_lines path = Validate_support.read_lines ~binary path

(* Reads a (timestamp,value) reference fixture. Timestamps are full RFC 3339
   (T00:00:00Z), parsed via Ptime.of_rfc3339; an empty value cell produces
   [Float.nan] so a NaN aggregate in the oracle round-trips (the daily fixture
   has none, but the reader encodes the shape, not the fixture). *)
let read_expected ~path : (Ptime.t * float) array =
  let lines = read_lines path in
  match lines with
  | [] -> die_tooling "%s: empty file" path
  | header :: rest ->
      if String.trim header <> "timestamp,value" then
        die_tooling "%s: expected header 'timestamp,value', got %S" path
          (String.trim header);
      List.mapi
        (fun i line ->
          let line_num = i + 2 in
          match String.split_on_char ',' line with
          | [ ts; v ] ->
              let ptime =
                match Ptime.of_rfc3339 (String.trim ts) with
                | Ok (t, _, _) -> t
                | Error _ ->
                    die_tooling "%s line %d: cannot parse %S as RFC 3339" path
                      line_num ts
              in
              let value =
                let trimmed = String.trim v in
                if trimmed = "" then Float.nan
                else
                  match Float.of_string_opt trimmed with
                  | Some f -> f
                  | None ->
                      die_tooling "%s line %d: cannot parse %S as float" path
                        line_num trimmed
              in
              (ptime, value)
          | _ ->
              die_tooling "%s line %d: expected 2 columns, got %S" path line_num
                line)
        rest
      |> Array.of_list

let float_close a b = Validate_support.float_close ~tolerance a b

(* Compares an actual monthly series against the expected (timestamp,value)
   reference, checking labels exactly (Ptime.equal) and values under the
   NaN-aware tolerance. Returns the max absolute value deviation on agreement. *)
let compare_monthly ~name ~expected ~actual_ts ~actual_v : float =
  let elen = Array.length expected in
  let alen = Array.length actual_ts in
  if elen <> alen then
    die_mismatch "%s: length mismatch — expected %d buckets, got %d" name elen
      alen;
  let max_diff = ref 0.0 in
  for i = 0 to elen - 1 do
    let ets, ev = expected.(i) in
    let ats = actual_ts.(i) and av = actual_v.(i) in
    if not (Ptime.equal ets ats) then
      die_mismatch "%s: bucket %d label mismatch — expected %s, got %s" name i
        (Ptime.to_rfc3339 ets) (Ptime.to_rfc3339 ats);
    if not (float_close ev av) then
      die_mismatch
        "%s: bucket %d (%s) value expected %.17g, got %.17g (diff %.17g)" name i
        (Ptime.to_rfc3339 ets) ev av
        (Float.abs (ev -. av));
    let d =
      if Float.is_nan ev || Float.is_nan av then 0.0 else Float.abs (ev -. av)
    in
    if d > !max_diff then max_diff := d
  done;
  !max_diff

let resample_monthly ~agg series =
  match Resample.resample ~agg Freq.Month series with
  | Ok s -> s
  | Error e -> die_tooling "resample to monthly: %s" (Resample.err_to_string e)

(* The final source month (March 2025) is truncated at 2025-03-14, mid-month.
   A truncated month must be matched as a real bucket, not dropped. The compare
   above already pins its label and value; this asserts the truncated month is the
   last emitted bucket so the requirement fails loudly if a future change trims
   partial months. *)
let assert_truncated_final_bucket ~name ~actual_ts =
  let n = Array.length actual_ts in
  if n = 0 then die_mismatch "%s: no monthly buckets emitted" name;
  let year, month, day = Ptime.to_date actual_ts.(n - 1) in
  if not (year = 2025 && month = 3 && day = 1) then
    die_mismatch
      "%s: final bucket label expected 2025-03-01, got %s (truncated March \
       2025 month must survive as a bucket)"
      name
      (Ptime.to_rfc3339 actual_ts.(n - 1))

let () =
  let input_path = Filename.concat fixture_dir "resample_daily_input.csv" in
  let sum_path =
    Filename.concat fixture_dir "resample_monthly_sum_expected.csv"
  in
  let last_path =
    Filename.concat fixture_dir "resample_monthly_last_expected.csv"
  in

  let daily = read_daily_series ~path:input_path in

  let run ~name ~agg ~expected_path =
    let out = resample_monthly ~agg daily in
    let actual_ts = Index.timestamps (Series.index out) in
    let actual_v = Nx.to_array (Series.values out) in
    let expected = read_expected ~path:expected_path in
    let d = compare_monthly ~name ~expected ~actual_ts ~actual_v in
    assert_truncated_final_bucket ~name ~actual_ts;
    d
  in

  let d_sum = run ~name:"sum" ~agg:`Sum ~expected_path:sum_path in
  let d_last = run ~name:"last" ~agg:`Last ~expected_path:last_path in

  Printf.eprintf
    "cross_validate_resample: daily->monthly Sum and Last match Pandas; max \
     value deviation %.17g\n"
    (Float.max d_sum d_last);
  exit 0
