(* Cross-validation harness for cairos Frame cross-sectional operations.

   Loads each fixture frame via Cairos_io.frame_of_csv, applies Frame.rank /
   Frame.zscore, and compares cell-by-cell against the Pandas-emitted
   expected-output frame. Exits 0 on full agreement at tolerance 1e-10,
   1 on any cell mismatch, 2 on tooling-level failure
   (missing fixture, malformed CSV).

   Pattern mirrors test/unit/cairos_finance/cross_validate.ml: this is an
   (executable), not a (test) — fixtures are generated by Python via
   `just validate-generate`, so `dune runtest` must not invoke it. The
   binary runs via `just validate-check` only. *)

open Cairos

let binary = "cross_validate_frame"
let fixture_dir = Validate_support.generated_fixture_dir
let die_tooling fmt = Validate_support.die_tooling ~binary fmt

let read_frame_fixture ~path : [ `Daily ] Frame.t =
  match Cairos_io.frame_of_csv ~freq:Freq.Day path with
  | Ok f -> f
  | Error e -> die_tooling "%s: %s" path (Cairos_io.err_to_string e)

(* NaN-aware tolerance comparator.
   Returns Ok max_abs_diff on agreement, Error msg on first mismatch. *)
let compare_columns ~tolerance ~column ~expected ~actual :
    (float, string) result =
  let elen = Array.length expected in
  let alen = Array.length actual in
  if elen <> alen then
    Error
      (Printf.sprintf "column %s: length mismatch: expected %d, got %d" column
         elen alen)
  else
    let max_diff = ref 0.0 in
    let rec check i =
      if i >= elen then Ok !max_diff
      else
        let e = expected.(i) and a = actual.(i) in
        let e_nan = Float.is_nan e and a_nan = Float.is_nan a in
        if e_nan && a_nan then check (i + 1)
        else if e_nan || a_nan then
          Error
            (Printf.sprintf
               "column %s row %d: expected %.17g, got %.17g (NaN mismatch)"
               column i e a)
        else
          let diff = Float.abs (e -. a) in
          if diff > tolerance then
            Error
              (Printf.sprintf
                 "column %s row %d: expected %.17g, got %.17g (diff %.17g)"
                 column i e a diff)
          else (
            if diff > !max_diff then max_diff := diff;
            check (i + 1))
    in
    check 0

let column_values frame name : float array =
  match Frame.get name frame with
  | Some s -> Nx.to_array (Series.values s)
  | None -> die_tooling "column %s not found in frame" name

let compare_frames ~tolerance ~expected ~actual : (float, string) result =
  let ecols = Nonempty.to_list (Frame.columns expected) in
  let acols = Nonempty.to_list (Frame.columns actual) in
  if ecols <> acols then
    Error
      (Printf.sprintf "column list mismatch: expected [%s], got [%s]"
         (String.concat "; " ecols) (String.concat "; " acols))
  else
    let rec walk acc = function
      | [] -> Ok acc
      | name :: rest -> (
          let expected_arr = column_values expected name in
          let actual_arr = column_values actual name in
          match
            compare_columns ~tolerance ~column:name ~expected:expected_arr
              ~actual:actual_arr
          with
          | Error _ as e -> e
          | Ok d -> walk (Float.max acc d) rest)
    in
    walk 0.0 ecols

let run_comparison ~name ~input_path ~expected_path ~op : (float, string) result
    =
  let input = read_frame_fixture ~path:input_path in
  let actual = op input in
  let expected = read_frame_fixture ~path:expected_path in
  match compare_frames ~tolerance:1e-10 ~expected ~actual with
  | Ok d -> Ok d
  | Error msg -> Error (Printf.sprintf "%s: %s" name msg)

let comparisons =
  let make fixture =
    let input =
      Filename.concat fixture_dir ("frame_xsec_" ^ fixture ^ ".csv")
    in
    [
      ( Printf.sprintf "rank/%s" fixture,
        input,
        Filename.concat fixture_dir
          ("frame_xsec_" ^ fixture ^ "_rank_expected.csv"),
        Frame.rank );
      ( Printf.sprintf "zscore/%s" fixture,
        input,
        Filename.concat fixture_dir
          ("frame_xsec_" ^ fixture ^ "_zscore_expected.csv"),
        Frame.zscore );
    ]
  in
  List.concat_map make
    [ "full"; "partial_nan"; "constant_row"; "single_column" ]

let () =
  let max_deviation = ref 0.0 in
  let failures = ref [] in
  List.iter
    (fun (name, input_path, expected_path, op) ->
      match run_comparison ~name ~input_path ~expected_path ~op with
      | Ok d -> if d > !max_deviation then max_deviation := d
      | Error msg -> failures := msg :: !failures)
    comparisons;
  match List.rev !failures with
  | [] ->
      Printf.eprintf
        "cross_validate_frame: %d comparison(s) passed; max cell deviation %.17g\n"
        (List.length comparisons) !max_deviation;
      exit 0
  | errs ->
      List.iter (fun m -> prerr_endline ("cross_validate_frame: " ^ m)) errs;
      exit 1
