(* Unit tests for the shared cross-check harness helpers.

   The comparator is the reason this file exists. Every harness that consumes
   [Validate_support.float_close] does so in a binary that [dune runtest] never
   invokes, and in a code path the shipped fixtures never reach: each harness
   forbids non-finite values outright and rejects them before the comparator is
   asked anything, so both NaN branches are unreachable in the binaries that
   depend on them being correct. "This stays the general comparator" is a claim,
   and this is where it is pinned rather than asserted.

   Mirrors the precedents already in the tree —
   [test/unit/cairos_finance/cross_validate.ml]'s two [compare_arrays] NaN cases
   and [test_qcheck_gen.ml]'s two [float_approx_equal] cases. Same convention,
   same two branches, third comparator.

   [die_tooling] and [die_mismatch] are not covered here: both terminate the
   process, so pinning them needs a subprocess rather than an Alcotest case.
   Their exit codes are exercised by the harnesses themselves — a missing
   fixture exits 2, a real disagreement exits 1 — and by
   [just validate-check] / [just validate-oracle] failing loudly rather than
   silently when either happens. *)

let tolerance = Validate_support.default_tolerance

let float_close_both_nan_are_equal () =
  Alcotest.(check bool)
    "both nan compare equal" true
    (Validate_support.float_close ~tolerance Float.nan Float.nan)

let float_close_one_sided_nan_is_unequal () =
  Alcotest.(check bool)
    "nan vs finite is unequal" false
    (Validate_support.float_close ~tolerance Float.nan 1.0);
  Alcotest.(check bool)
    "finite vs nan is unequal" false
    (Validate_support.float_close ~tolerance 1.0 Float.nan)

(* The branch that would exist even in a naive comparator, pinned so that a
   future edit to the NaN arms cannot quietly change the tolerance semantics
   underneath them. Exactly-at-tolerance is close, because the comparison is
   [<=]; every harness's reported "worst deviation ... tolerance 1e-10" line
   reads as a pass at equality.

   The pairs are anchored at [0.0] rather than [1.0] on purpose: [1.0 +. 1e-10]
   is not representable, so [(1.0 +. tolerance) -. 1.0] lands just above
   [tolerance] and the boundary case would be testing float representation
   rather than the comparator. Against zero the difference is exact. *)
let float_close_finite_pairs_use_absolute_tolerance () =
  Alcotest.(check bool)
    "difference below tolerance is close" true
    (Validate_support.float_close ~tolerance 0.0 (tolerance /. 2.0));
  Alcotest.(check bool)
    "difference exactly at tolerance is close" true
    (Validate_support.float_close ~tolerance 0.0 tolerance);
  Alcotest.(check bool)
    "difference above tolerance is not close" false
    (Validate_support.float_close ~tolerance 0.0 (tolerance *. 10.0));
  Alcotest.(check bool)
    "the comparison is absolute, not relative" false
    (Validate_support.float_close ~tolerance 1e12 (1e12 *. (1.0 +. 1e-9)))

(* Infinity is not NaN, so it takes the subtraction branch: [inf -. inf] is NaN
   and [Float.abs nan <= tol] is false. Two infinities are therefore NOT close.
   Pinned because it is the one result here that surprises, and because a
   harness that treats a regression to infinity as agreement would report a
   broken system as clean. *)
let float_close_infinities_are_not_close () =
  Alcotest.(check bool)
    "two positive infinities are not close" false
    (Validate_support.float_close ~tolerance Float.infinity Float.infinity);
  Alcotest.(check bool)
    "infinity vs finite is not close" false
    (Validate_support.float_close ~tolerance Float.infinity 1.0)

(* [abs_diff] feeds a running maximum. If a NaN operand returned NaN, [Float.max]
   would propagate the finite argument and the outlier would vanish from the
   reported worst deviation — the number's whole job is to surface it. *)
let abs_diff_nan_operand_yields_infinity () =
  Alcotest.(check (float 0.0))
    "nan on the left" Float.infinity
    (Validate_support.abs_diff Float.nan 1.0);
  Alcotest.(check (float 0.0))
    "nan on the right" Float.infinity
    (Validate_support.abs_diff 1.0 Float.nan);
  Alcotest.(check (float 0.0))
    "both nan" Float.infinity
    (Validate_support.abs_diff Float.nan Float.nan)

let abs_diff_is_symmetric_on_finite_pairs () =
  Alcotest.(check (float 1e-15))
    "left to right" 0.25
    (Validate_support.abs_diff 1.25 1.0);
  Alcotest.(check (float 1e-15))
    "right to left" 0.25
    (Validate_support.abs_diff 1.0 1.25)

(* The two fixture directories are not interchangeable: one is gitignored and
   regenerated by the default gate, the other is committed and written only by
   the opt-in oracles. A harness reading the wrong one still finds files and
   still compares numbers, which is the failure this pins. *)
let fixture_dirs_are_distinct () =
  Alcotest.(check string)
    "generated" "validation/fixtures" Validate_support.generated_fixture_dir;
  Alcotest.(check string)
    "committed" "validation/oracle_fixtures" Validate_support.oracle_fixture_dir

let () =
  Alcotest.run "validate_support"
    [
      ( "float_close",
        [
          Alcotest.test_case "both nan are equal" `Quick
            float_close_both_nan_are_equal;
          Alcotest.test_case "one-sided nan is unequal" `Quick
            float_close_one_sided_nan_is_unequal;
          Alcotest.test_case "finite pairs use absolute tolerance" `Quick
            float_close_finite_pairs_use_absolute_tolerance;
          Alcotest.test_case "infinities are not close" `Quick
            float_close_infinities_are_not_close;
        ] );
      ( "abs_diff",
        [
          Alcotest.test_case "nan operand yields infinity" `Quick
            abs_diff_nan_operand_yields_infinity;
          Alcotest.test_case "symmetric on finite pairs" `Quick
            abs_diff_is_symmetric_on_finite_pairs;
        ] );
      ( "constants",
        [
          Alcotest.test_case "fixture dirs are distinct" `Quick
            fixture_dirs_are_distinct;
        ] );
    ]
