(** Helpers shared by the validation cross-check executables.

    Those binaries are [executable]s, not [test]s: they read fixtures produced
    outside dune and run from [just validate-check] and [just validate-oracle],
    never from [dune runtest]. Their failure convention is an exit code rather
    than a [result] — exit [2] for a tooling failure (missing or malformed
    fixture, unreadable file) and exit [1] for a genuine mismatch between a
    system and its reference. That distinction is what lets a caller tell "the
    harness could not run" from "the harness ran and the numbers disagree", so
    it is worth keeping straight at every call site.

    Lifted here when the fourth harness needed the same three helpers. The
    copies had already drifted — one filtered blank lines before trimming and
    the others after — which is how a fixture-format change ends up half
    applied.

    [test/unit/cairos_engine/cross_validate.ml] deliberately keeps its own
    copies. Feature 0063 FR-1 makes that file's being unmodified the evidence
    that its green run says something about the clean-room reference rather than
    about the comparison, so it is migrated in a later change, not this one. *)

val generated_fixture_dir : string
(** [validation/fixtures]: regenerated by [just validate-generate], gitignored.
*)

val oracle_fixture_dir : string
(** [validation/oracle_fixtures]: committed to the repository, written by the
    two opt-in third-party oracles. *)

val default_tolerance : float
(** Absolute [1e-10]. Every harness compares floats at this tolerance. *)

val die_tooling : binary:string -> ('a, unit, string, 'b) format4 -> 'a
(** [die_tooling ~binary fmt] reports a tooling failure on stderr and exits [2].

    Use for anything that means the harness could not do its job: a missing
    fixture, an unparseable cell, a header that is not what the writer promised.
    stdout is flushed first, so buffered per-scenario progress lines cannot land
    after the error and read as though the scenarios following the failing one
    passed. *)

val die_mismatch : binary:string -> ('a, unit, string, 'b) format4 -> 'a
(** [die_mismatch ~binary fmt] reports a mismatch on stderr and exits [1].

    Use only when the harness ran correctly and the systems disagree. A
    malformed fixture is not a mismatch: reporting one as the other tells the
    operator that the code is wrong when the data is. *)

val read_lines : binary:string -> string -> string list
(** [read_lines ~binary path] reads [path] and returns its non-blank lines,
    blank being measured after trimming. Exits [2] if the file cannot be read.
*)

val float_close : tolerance:float -> float -> float -> bool
(** NaN-aware and symmetric absolute comparison.

    Both operands are tested for NaN before the subtraction, because
    [Float.abs (nan -. x) <= tol] is [false] for every [x] including [nan]: a
    naive comparator reports a regression to NaN as an ordinary mismatch, and
    reports both-NaN as a mismatch too, for the same wrong reason. Two NaNs
    compare equal here. A harness that additionally forbids NaN outright
    enforces that separately, so that this stays the general comparator. *)

val abs_diff : float -> float -> float
(** [Float.abs (a -. b)], or [infinity] if either operand is NaN.

    Used for reporting the worst deviation seen. Returning [infinity] rather
    than NaN keeps a running maximum meaningful: [Float.max] with NaN would
    silently swallow the outlier the number exists to surface. *)
